# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_components.ipynb.

# %% auto #0
__all__ = ['Layout', 'PostCard', 'FeaturedPost', 'FilterSection', 'PostContent', 'AboutContent', 'ContactForm', 'NotFoundContent']

# %% nbs/01_components.ipynb #87fb4f51-0a47-44cd-978a-9b7a58a8159b
from fasthtml.common import *
from monsterui.all import *
from datetime import datetime
from utils import extract_toc, render_post_md

# %% nbs/01_components.ipynb #07b740f2-ccaf-4172-88b9-1e838c7651ec
def Layout(*children, title="My Blog", wide=False):
    """Main layout component with floating navigation and footer"""
    content_cls = "max-w-5xl mx-auto" if wide else "max-w-3xl mx-auto"
    return (
        Title(title),
        # Floating navigation bar
        Nav(
            Div(
                A("Ivan Dolgushev", href="/",
                  cls="text-lg font-bold text-gray-900 hover:text-blue-600 transition-colors"),
                Div(
                    A("Home", href="/", cls="text-sm font-medium text-gray-600 hover:text-blue-600 transition-colors"),
                    A("About", href="/about", cls="text-sm font-medium text-gray-600 hover:text-blue-600 transition-colors"),
                    A("Contact", href="/contact", cls="text-sm font-medium text-gray-600 hover:text-blue-600 transition-colors"),
                    cls="flex gap-6 items-center"
                ),
                cls="flex justify-between items-center w-full max-w-2xl px-6"
            ),
            cls=("fixed top-6 left-1/2 -translate-x-1/2 z-50 "
                 "glass-nav rounded-full py-6 px-4 w-[90%] max-w-3xl "
                 "transition-all duration-300 hover:shadow-xl hover:-translate-y-0.5")
        ),

        # Main content area
        Container(
            Div(children, cls=content_cls),
            # Footer
            Footer(
                Div(
                    P(f"© {datetime.now().year} Ivan Dolgushev. Built with FastHTML & MonsterUI.",
                      cls="text-sm text-gray-500"),
                    A("RSS Feed", href="/feed",
                      cls="text-sm text-blue-600 hover:underline font-medium"),
                    cls="flex items-center justify-between flex-wrap gap-4"
                ),
                cls="py-12 mt-20 border-t border-gray-100"
            ),
            cls="min-h-screen px-4 pt-32 pb-12 glass-bg"
        )
    )

# %% nbs/01_components.ipynb #7e7e27da-6cb4-4c88-9bef-e3140d8e33de
def PostCard(post: dict):
    """Clickable post preview card"""
    date_str = post['date'].strftime('%d %b %Y')
    read_time = post.get('read_time', 1)
    return A(
        Div(
            H3(post['title'],
               cls="text-xl font-medium text-gray-900 group-hover:text-blue-600 transition-colors"),
            Div(
                Span(date_str, cls="text-sm text-gray-500"),
                Span("·", cls="text-gray-300"),
                Span(f"{read_time} min read", cls="text-sm text-gray-400"),
                cls="flex items-center gap-2 ml-auto shrink-0"
            ),
            cls="flex items-baseline justify-between gap-4"
        ),
        P(post['excerpt'], cls="text-gray-600 mt-2 text-sm leading-relaxed"),
        Div(
            *[Span(f"#{tag}", cls="text-xs font-semibold text-blue-600 bg-blue-50 px-2 py-1 rounded-full")
              for tag in post.get('tags', [])],
            cls="mt-3 flex flex-wrap gap-2"
        ),
        href=f"/post/{post['slug']}",
        cls="block py-6 px-4 mb-4 glass-card glass-card-hover rounded-xl group"
    )

def FeaturedPost(post: dict):
    """Large hero card for the pinned/featured post at top of homepage"""
    date_str = post['date'].strftime('%d %b %Y')
    read_time = post.get('read_time', 1)
    return Div(
        Span("Featured", cls="text-xs font-bold uppercase tracking-widest text-blue-600 bg-blue-50 px-3 py-1 rounded-full"),
        A(
            H2(post['title'],
               cls="text-3xl font-bold text-gray-900 mt-4 mb-3 group-hover:text-blue-600 transition-colors leading-snug"),
            P(post['excerpt'], cls="text-gray-600 text-base leading-relaxed mb-4"),
            Div(
                Span(date_str, cls="text-sm text-gray-500"),
                Span("·", cls="text-gray-300"),
                Span(f"{read_time} min read", cls="text-sm text-gray-400"),
                Div(
                    *[Span(f"#{tag}", cls="text-xs font-semibold text-blue-600 bg-blue-50 px-2 py-1 rounded-full")
                      for tag in post.get('tags', [])],
                    cls="flex flex-wrap gap-2 ml-auto"
                ),
                cls="flex items-center gap-3"
            ),
            href=f"/post/{post['slug']}",
            cls="block group"
        ),
        cls="mb-10 p-8 glass-card rounded-2xl featured-post-card"
    )

# %% nbs/01_components.ipynb #fd92183b-9442-45ef-8151-9de6906fd4a8
def FilterSection(all_categories: list[str], selected_categories: list[str], enabled_categories: list[str]):
    """Category filter chips with multi-select support"""
    
    def build_url(cats):
        return f"/?{'&'.join([f'category={c}' for c in cats])}" if cats else "/"

    def chip(cat, label=None):
        """Render category filter chip"""
        is_all = cat is None
        is_selected = (not selected_categories) if is_all else (cat in selected_categories)
        is_enabled = is_all or cat in enabled_categories
        
        # calculate next state
        if is_all: next_cats = []
        elif is_selected: next_cats = [c for c in selected_categories if c != cat]
        else: next_cats = selected_categories + [cat]
  
        if is_selected: cls = "glass-chip-active text-white"
        elif is_enabled: cls = "glass-chip text-gray-700 hover:bg-white/80"
        else: cls = "glass-chip-disabled text-gray-400"
            
        return A(label or cat.title(), 
                href=build_url(next_cats) if is_enabled else "#",
                cls=f"px-4 py-2 rounded-full text-sm font-medium transition-all {cls}")

    return Div(
        chip(None, "All"),
        *[chip(cat) for cat in all_categories],
        cls="flex flex-wrap gap-2 justify-center mb-12"
    )

# %% nbs/01_components.ipynb #59f3bb51-8acb-4ca0-b0c5-bf521589a013
def _StickyTOC(toc: list):
    """Sticky table-of-contents sidebar"""
    items = []
    for level, text, slug in toc:
        indent = "pl-4 text-gray-400" if level == 3 else "text-gray-500"
        items.append(A(text, href=f"#{slug}",
                       cls=f"block text-sm hover:text-blue-600 transition-colors py-1 toc-link {indent}"))
    return Div(
        P("On this page", cls="text-xs font-bold uppercase tracking-widest text-gray-400 mb-3"),
        Div(*items),
        cls="toc-sticky glass-card rounded-xl p-5"
    )

def PostContent(post: dict):
    """Full post content with optional sticky TOC for posts with headings"""
    date_str = post['date'].strftime('%B %d, %Y') if isinstance(post['date'], datetime) else str(post['date'])
    read_time = post.get('read_time', 1)
    toc = extract_toc(post['content'])
    rendered = render_post_md(post['content'])

    article = Article(
        Header(
            H1(post['title'], cls="text-5xl font-bold mb-4 text-gray-900"),
            Div(
                Span(date_str, cls="text-gray-500"),
                Span("·", cls="text-gray-300 mx-2"),
                Span(f"{read_time} min read", cls="text-gray-400"),
                cls="flex items-center mb-8"
            ),
            cls="mb-8"
        ),
        NotStr(rendered),
        Footer(
            A("← Back to Home", href="/",
              cls="inline-block px-4 py-2 border-2 border-blue-600 text-blue-600 rounded-lg hover:bg-blue-600 hover:text-white transition-colors mt-12")
        ),
        cls="py-8 glass-card p-8 rounded-2xl min-w-0"
    )

    if not toc: return article
    return Div(
        article,
        Div(_StickyTOC(toc), cls="toc-column"),
        Script("""
            const links = document.querySelectorAll('.toc-link');
            const obs = new IntersectionObserver(entries => {
                entries.forEach(e => {
                    const l = document.querySelector(`.toc-link[href="#${e.target.id}"]`);
                    if (l) l.classList.toggle('toc-active', e.isIntersecting);
                });
            }, {rootMargin: '-10% 0px -70% 0px'});
            document.querySelectorAll('h2[id], h3[id]').forEach(h => obs.observe(h));
        """),
        cls="post-with-toc"
    )

# %% nbs/01_components.ipynb #9ed832c5-b8b1-4fb3-b2ed-ede594775789
def AboutContent():
    """About page content"""
    return Div(
        H1("About Me", cls="text-4xl font-bold mb-8 text-gray-900"),
        Div(
            P("I'm Ivan Dolgushev — I build ML systems and write about the messy parts of production machine learning, Python tooling, and the occasional side project.",
              cls="mb-5 text-lg leading-relaxed text-gray-700"),
            P("My day job involves training and deploying models at scale. Outside of that, I write here to make sense of what I'm learning — and to share what I wish had existed when I was figuring these things out myself.",
              cls="mb-5 text-lg leading-relaxed text-gray-700"),
            P("This blog covers:", cls="mb-3 text-lg font-medium text-gray-900"),
            Ul(
                Li("Production ML: training loops, evaluation, and deployment pipelines"),
                Li("Python ecosystem: FastHTML, fast.ai, and tooling I find genuinely useful"),
                Li("Side projects: the process, not just the polished result"),
                cls="list-disc pl-6 mb-8 text-lg text-gray-700 space-y-2"
            ),
            H2("Find me elsewhere", cls="text-2xl font-semibold mb-4 mt-8 text-gray-900"),
            Div(
                A("GitHub", href="https://github.com/ivandolgushev",
                  cls="text-blue-600 hover:underline font-medium"),
                Span("·", cls="text-gray-300 mx-2"),
                A("RSS Feed", href="/feed",
                  cls="text-blue-600 hover:underline font-medium"),
                Span("·", cls="text-gray-300 mx-2"),
                A("Email", href="mailto:ivandolgushev@gmail.com",
                  cls="text-blue-600 hover:underline font-medium"),
                cls="text-lg"
            ),
            cls="max-w-2xl"
        )
    )

# %% nbs/01_components.ipynb #ce526a67-4fdf-49bd-b963-7600ca2e58a2
def ContactForm():
    """Contact form component"""
    return Div(
        H1("Contact Me", cls="text-4xl font-bold mb-6"),
        Form(
            LabelInput("Name", id="name", placeholder="Your name"),
            LabelInput("Email", id="email", type="email", placeholder="your@email.com"),
            LabelTextArea("Message", id="message", rows=5, placeholder="What's on your mind?"),
            Button("Send Message", cls=ButtonT.primary),
            action="/contact/submit", method="post",
            cls="space-y-4 max-w-lg bg-white shadow-lg p-8 rounded-lg"
        )
    )

# %% nbs/01_components.ipynb #d88c78fd-d873-4fa6-9ba0-dc9730a6ea2b
def NotFoundContent():
    """404 page content"""
    return Div(
        H1("404 - Page Not Found", cls="text-4xl font-bold text-center mt-20"),
        P("The page you're looking for doesn't exist.", cls="text-center mt-4 text-lg text-gray-600"),
        Div(
            A("Go Home", href="/",
              cls="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors mt-6"),
            cls="text-center"
        )
    )
