# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_main.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'index', 'post_page', 'about', 'contact', 'contact_submit']

# %% nbs/03_main.ipynb 3
from fasthtml.common import *
from monsterui.all import *
from components import *
from utils import *

# %% nbs/03_main.ipynb 4
app, rt = fast_app(hdrs=Theme.blue.headers(highlightjs=True), static_path="static")

# %% nbs/03_main.ipynb 5
@rt("/")
def index(category: list[str] = None):
    """Homepage listing all blog posts"""
    all_posts = load_all_posts()
    all_posts.sort(key=lambda p: p['date'], reverse=True)

    selected_cats = [c.lower() for c in category] if category else []
    posts = filter_posts(all_posts, selected_cats)
    all_tags = get_all_tags()
    enabled_tags = get_enabled_tags(all_posts, selected_cats, all_tags)

    return Layout(
        # Hero section
        Div(
            H1("Ivan Dolgushev", cls="text-4xl font-bold mb-3 text-gray-900"),
            P("Software engineer, writer, and technology enthusiast.",
              cls="text-xl text-gray-600 mb-8"),
            cls="mb-12"
        ),
        
        # Filter Section
        FilterSection(all_tags, selected_cats, list(enabled_tags)),

        # Blog posts section
        Div(
            H2("Recent Posts", cls="text-2xl font-bold mb-6 text-gray-900"),
            Div(
                *[PostCard(post) for post in posts] if posts else [
                    P("No blog posts yet. Check back soon!", cls="text-gray-600 py-6")
                ],
                cls="divide-y divide-gray-200"
            ),
            cls="mb-12"
        ),
        title="Ivan Dolgushev - Personal Blog"
    )

@app.get("/post/{slug}")
def post_page(slug: str):
    """Individual blog post page"""
    post = load_post_by_slug(slug)
    if not post: return Layout(NotFoundContent(), title="404 - Not Found" ), 404
    return Layout(PostContent(post), title=f"{post['title']} - My Blog")

@app.get("/about")
def about():
    """About page"""
    return Layout(AboutContent(), title="About - My Blog")

@app.get("/contact")
def contact():
    """Contact page"""
    return Layout(ContactForm(),title="Contact - My Blog")

@app.post("/contact/submit")
async def contact_submit(name: str, email: str, message: str):
    """Handle contact form submission"""
    # TODO: Send email or save to database
    return Layout(
        Div(
            H1("Thank You!", cls="text-4xl font-bold mb-4 text-center text-success"),
            P(f"Thanks for reaching out, {name}!", cls="text-center text-lg mb-2"),
            P("Your message has been received. I'll get back to you soon!", cls="text-center text-gray-600 mb-6"),
            Div(A(Button("Back to Home", cls=ButtonT.primary), href="/"), cls="text-center"),
            cls="py-12"
        ),
        title="Message Sent - My Blog"
    )

# %% nbs/03_main.ipynb 9
serve()
