# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_utils.ipynb.

# %% auto #0
__all__ = ['BASE_DIR', 'POSTS_DIR', 'load_post_by_slug', 'load_all_posts', 'get_all_tags', 'filter_posts', 'get_enabled_tags',
           'extract_slug_from_filename', 'calc_read_time', 'extract_toc', 'render_post_md']

# %% nbs/02_utils.ipynb #7e9b6b7e-783f-4bc3-9ed7-00c9f1ad81c7
from fasthtml.common import *
from monsterui.all import render_md
import frontmatter
import re
from pathlib import Path
from datetime import datetime

# %% nbs/02_utils.ipynb #dccc016d-d1f3-47f0-9f90-4c23bd12a965
BASE_DIR = Path.cwd()
if BASE_DIR.name == 'nbs': BASE_DIR = BASE_DIR.parent
POSTS_DIR = Path(f"{BASE_DIR}/posts")

# %% nbs/02_utils.ipynb #dde5a3f2-ba2e-47af-a984-7b5249e9ebb8
def calc_read_time(content: str) -> int:
    """Estimate reading time in minutes at ~200 wpm"""
    return max(1, round(len(content.split()) / 200))

def _slugify(text: str) -> str:
    return re.sub(r'[-\s]+', '-', re.sub(r'[^\w\s-]', '', text.lower())).strip('-')

def extract_toc(content: str) -> list:
    """Extract (level, text, slug) tuples for h2/h3 headings from markdown source"""
    counter, headings = {}, []
    for m in re.finditer(r'^(#{2,3})\s+(.+)', content, re.MULTILINE):
        level, text = len(m.group(1)), m.group(2).strip()
        slug = _slugify(text)
        counter[slug] = counter.get(slug, 0) + 1
        if counter[slug] > 1: slug = f"{slug}-{counter[slug]}"
        headings.append((level, text, slug))
    return headings

def render_post_md(content: str) -> str:
    """Render markdown with id attrs injected on h2/h3 headings for TOC anchors"""
    counter = {}
    def _add_id(m):
        lvl, attrs, inner = m.group(1), m.group(2), m.group(3)
        slug = _slugify(re.sub(r'<[^>]+>', '', inner))
        counter[slug] = counter.get(slug, 0) + 1
        if counter[slug] > 1: slug = f"{slug}-{counter[slug]}"
        return f'<h{lvl} id="{slug}"{attrs}>{inner}</h{lvl}>'
    return re.sub(r'<h([23])([^>]*)>(.*?)</h\1>', _add_id, str(render_md(content)), flags=re.DOTALL)

def load_post_by_slug(slug: str) -> Optional[Dict]:
    """Load a single post by its slug."""
    for post_file in POSTS_DIR.glob("*.md"):
        if slug in post_file.stem: post = frontmatter.load(post_file)
    return {
        'slug': slug,
        'title': post.get('title', 'Untitled'),
        'date': post.get('date', datetime.now()),
        'tags': post.get('tags', []),
        'excerpt': post.get('excerpt', ''),
        'content': post.content,
        'read_time': calc_read_time(post.content)
    }

    return None

# %% nbs/02_utils.ipynb #e1ca855f-263d-47cc-b784-e09bbb0feff2
def load_all_posts() -> List[Dict]:
    """Load all blog posts from the posts directory."""
    if not POSTS_DIR.exists(): return []
    posts = []
    for post_file in POSTS_DIR.glob("*.md"):
        post = frontmatter.load(post_file)
        slug = extract_slug_from_filename(post_file.name)
        posts.append({
            'slug': slug,
            'title': post.get('title', 'Untitled'),
            'date': post.get('date', datetime.now()),
            'tags': post.get('tags', []),
            'excerpt': post.get('excerpt', ''),
            'featured': post.get('featured', False),
            'read_time': calc_read_time(post.content)
        })
    return posts

# %% nbs/02_utils.ipynb #b6662fe0-7ee3-4c33-ab31-4315fabe49c6
def get_all_tags() -> List[str]:
    """Get sorted list of all unique tags across all posts"""
    tags = set()
    posts = load_all_posts()
    for post in posts: tags.update(post.get('tags', []))
    return sorted(list(tags))

# %% nbs/02_utils.ipynb #73f114c7-fb58-4d78-9c97-c11c19dba1bb
def filter_posts(posts: List[Dict], selected_cats: List[str]) -> List[Dict]:
    """Filter posts by selected categories usin AND logic"""
    if not selected_cats: return posts
    return [p for p in posts if all(cat in p.get('tags', []) for cat in selected_cats)]

# %% nbs/02_utils.ipynb #020f092f-ef34-4367-8c76-7a475c9f0914
def get_enabled_tags(all_posts: List[Dict], selected_cats: List[str], all_tags: List[str]) -> List[str]:
    """Calculate which tags should be enabled based on current selection"""
    if not selected_cats:
        # No filters: enable all tags that appear in at least one post
        return [tag for tag in all_tags if any(tag in p.get('tags', []) for p in all_posts)]

    enabled_tags = set()
    for tag in all_tags:
        # Already selected tags are always enabled (for removal)
        if tag in selected_cats:
            enabled_tags.add(tag)
            continue
        
        # Check if adding this tag would still return posts
        test_cats = selected_cats + [tag]
        if filter_posts(all_posts, test_cats): enabled_tags.add(tag)
            
    return list(enabled_tags)

# %% nbs/02_utils.ipynb #190bf805-2984-4f1f-85ab-0001df8ffdbe
def extract_slug_from_filename(filename: str) -> str:
    """Extract slug from filename (format: YYYY-MM-DD-slug-name.md)"""
    stem = Path(filename).stem
    parts = stem.split('-')
    # Skip first 3 parts (year, month, day)
    return '-'.join(parts[3:]) if len(parts) > 3 else stem
