# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_utils.ipynb.

# %% auto 0
__all__ = ['POSTS_DIR', 'load_post_by_slug', 'load_all_posts', 'get_all_tags', 'filter_posts', 'get_enabled_tags',
           'extract_slug_from_filename']

# %% nbs/02_utils.ipynb 1
from fasthtml.common import *
import frontmatter
# import markdown
from pathlib import Path
from datetime import datetime

# %% nbs/02_utils.ipynb 2
POSTS_DIR = Path("../posts")

# %% nbs/02_utils.ipynb 3
def load_post_by_slug(slug: str) -> Optional[Dict]:
    """Load a single post by its slug."""
    # Try to find the post file matching the slug
    for post_file in POSTS_DIR.glob("*.md"):
        if slug in post_file.stem: post = frontmatter.load(post_file)
        return {
            'slug': slug,
            'title': post.get('title', 'Untitled'),
            'date': post.get('date', datetime.now()),
            'tags': post.get('tags', []),
            'excerpt': post.get('excerpt', ''),
            'content': post.content,
        }

    return None

# %% nbs/02_utils.ipynb 4
def load_all_posts() -> List[Dict]:
    """Load all blog posts from the posts directory."""
    if not POSTS_DIR.exists(): return []
    posts = []
    for post_file in POSTS_DIR.glob("*.md"):
        post = frontmatter.load(post_file)
        slug = extract_slug_from_filename(post_file.name)
        posts.append({
            'slug': slug,
            'title': post.get('title', 'Untitled'),
            'date': post.get('date', datetime.now()),
            'tags': post.get('tags', []),
            'excerpt': post.get('excerpt', '')
        })

    return posts

# %% nbs/02_utils.ipynb 5
def get_all_tags() -> List[str]:
    """Get sorted list of all unique tags across all posts"""
    tags = set()
    posts = load_all_posts()
    for post in posts: tags.update(post.get('tags', []))
    return sorted(list(tags))

# %% nbs/02_utils.ipynb 6
def filter_posts(posts: List[Dict], selected_cats: List[str]) -> List[Dict]:
    """Filter posts by selected categories usin AND logic"""
    if not selected_cats: return posts
    return [p for p in posts if all(cat in p.get('tags', []) for cat in selected_cats)]

# %% nbs/02_utils.ipynb 7
def get_enabled_tags(all_posts: List[Dict], selected_cats: List[str], all_tags: List[str]) -> List[str]:
    """Calculate which tags should be enabled based on current selection"""
    if not selected_cats:
        # No filters: enable all tags that appear in at least one post
        return [tag for tag in all_tags if any(tag in p.get('tags', []) for p in all_posts)]

    enabled_tags = set()
    for tag in all_tags:
        # Already selected tags are always enabled (for removal)
        if tag in selected_cats:
            enabled_tags.add(tag)
            continue
        
        # Check if adding this tag would still return posts
        test_cats = selected_cats + [tag]
        if filter_posts(all_posts, test_cats): enabled_tags.add(tag)
            
    return list(enabled_tags)

# %% nbs/02_utils.ipynb 9
def extract_slug_from_filename(filename: str) -> str:
    """Extract slug from filename (format: YYYY-MM-DD-slug-name.md)"""
    stem = Path(filename).stem
    parts = stem.split('-')
    # Skip first 3 parts (year, month, day)
    return '-'.join(parts[3:]) if len(parts) > 3 else stem
